# Numpy practise

In [5]:
import numpy as np

## Array Boot Camp

In [6]:
arr_1d = np.array([10,20 ,30,40,50])
arr_2d = np.zeros((3,4))
arr2_2d = np.ones((3,4))
arr_r  =np.arange(0, 50,5)
arr_li = np.linspace(0, 1, 20)
arr_eye = np.eye(4)
print(" 1D Array:\n", arr_1d)
print(" 2D Array (Zeros):\n", arr_2d)
print(" 2D Array (Ones):\n", arr2_2d)
print(" Range Array:\n", arr_r)
print(" Linearly Spaced Array:\n", arr_li)
print(" Identity Matrix:\n", arr_eye)

 1D Array:
 [10 20 30 40 50]
 2D Array (Zeros):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 2D Array (Ones):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 Range Array:
 [ 0  5 10 15 20 25 30 35 40 45]
 Linearly Spaced Array:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Data Type Detective

In [7]:
arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int8)
arr_float = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float64)
arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
arr_int32 = np.array([1, 2, 3, 3, 6], dtype=np.int32)
arr_converted = arr_float.astype(np.int32)
arr = np.array([15, 22, 8, 33, 5])
arr_bool = arr > 10
print(" Integer Array:\n", arr_int.itemsize, "bytes per element")
print(" Float Array:\n", arr_float.itemsize, "bytes per element")
print(" Complex Array:\n", arr_complex.itemsize, "bytes per element")
print(" Converted Array:\n", arr_converted.itemsize, "bytes per element")
print(" Data Type:\n", arr_converted.dtype)
print(" Original Array:\n", arr_float)
print(" Converted Array:\n", arr_converted)
print(" Boolean Array:\n", arr_bool)

 Integer Array:
 1 bytes per element
 Float Array:
 8 bytes per element
 Complex Array:
 16 bytes per element
 Converted Array:
 4 bytes per element
 Data Type:
 int32
 Original Array:
 [1. 2. 3. 4. 5.]
 Converted Array:
 [1 2 3 4 5]
 Boolean Array:
 [ True  True False  True False]


## Reshape & Slice Master

In [8]:
arr = np.arange(1, 13)
print(" Original Array:\n", arr)
arr_reshaped = arr.reshape(3, 4)
print(" Reshaped Array (3x4):\n", arr_reshaped)
print("the second row of the reshaped array:\n", arr_reshaped[1])
print("the third row of the reshaped array:\n", arr_reshaped[2])
a = arr_reshaped[1:3,2:5]
print("the subarray:\n", a)
arr_transposed = arr_reshaped.T
print(" Transposed Array:\n", arr_transposed.shape)


 Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the second row of the reshaped array:
 [5 6 7 8]
the third row of the reshaped array:
 [ 9 10 11 12]
the subarray:
 [[ 7  8]
 [11 12]]
 Transposed Array:
 (4, 3)


## Broadcasting Challenge

In [12]:
arr_onez = np.ones((3, 3))
arr = np.array([10,20,30])
arr_added = arr_onez + arr
print("Array:\n", arr_added)
arr_3d = np.array([[10], [20], [30]])
ne_arr = arr * arr_3d
print("New Array:\n", ne_arr.shape)

Array:
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]
New Array:
 (3, 3)
