# Numpy practise

In [2]:
import numpy as np

## Array Boot Camp

In [3]:
arr_1d = np.array([10,20 ,30,40,50])
arr_2d = np.zeros((3,4))
arr2_2d = np.ones((3,4))
arr_r  =np.arange(0, 50,5)
arr_li = np.linspace(0, 1, 20)
arr_eye = np.eye(4)
print(" 1D Array:\n", arr_1d)
print(" 2D Array (Zeros):\n", arr_2d)
print(" 2D Array (Ones):\n", arr2_2d)
print(" Range Array:\n", arr_r)
print(" Linearly Spaced Array:\n", arr_li)
print(" Identity Matrix:\n", arr_eye)

 1D Array:
 [10 20 30 40 50]
 2D Array (Zeros):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 2D Array (Ones):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 Range Array:
 [ 0  5 10 15 20 25 30 35 40 45]
 Linearly Spaced Array:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Data Type Detective

In [4]:
arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int8)
arr_float = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float64)
arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
arr_int32 = np.array([1, 2, 3, 3, 6], dtype=np.int32)
arr_converted = arr_float.astype(np.int32)
arr = np.array([15, 22, 8, 33, 5])
arr_bool = arr > 10
print(" Integer Array:\n", arr_int.itemsize, "bytes per element")
print(" Float Array:\n", arr_float.itemsize, "bytes per element")
print(" Complex Array:\n", arr_complex.itemsize, "bytes per element")
print(" Converted Array:\n", arr_converted.itemsize, "bytes per element")
print(" Data Type:\n", arr_converted.dtype)
print(" Original Array:\n", arr_float)
print(" Converted Array:\n", arr_converted)
print(" Boolean Array:\n", arr_bool)

 Integer Array:
 1 bytes per element
 Float Array:
 8 bytes per element
 Complex Array:
 16 bytes per element
 Converted Array:
 4 bytes per element
 Data Type:
 int32
 Original Array:
 [1. 2. 3. 4. 5.]
 Converted Array:
 [1 2 3 4 5]
 Boolean Array:
 [ True  True False  True False]


## Reshape & Slice Master

In [5]:
arr = np.arange(1, 13)
print(" Original Array:\n", arr)
arr_reshaped = arr.reshape(3, 4)
print(" Reshaped Array (3x4):\n", arr_reshaped)
print("the second row of the reshaped array:\n", arr_reshaped[1])
print("the third row of the reshaped array:\n", arr_reshaped[2])
a = arr_reshaped[1:3,2:5]
print("the subarray:\n", a)
arr_transposed = arr_reshaped.T
print(" Transposed Array:\n", arr_transposed.shape)


 Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the second row of the reshaped array:
 [5 6 7 8]
the third row of the reshaped array:
 [ 9 10 11 12]
the subarray:
 [[ 7  8]
 [11 12]]
 Transposed Array:
 (4, 3)


## Broadcasting Challenge

In [ ]:
arr_onez = np.ones((3, 3))
arr = np.array([10,20,30])
arr_added = arr_onez + arr
print("Array:\n", arr_added)
arr_3d = np.array([[10], [20], [30]])
ne_arr = arr * arr_3d
print("New Array:\n", ne_arr.shape)

Array:
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]
New Array:
 (3, 3)


In [12]:
data = np.random.rand(4, 3)
col_means = data.mean(axis=0)
col_stds = data.std(axis=0)
normalized_data = (data - col_means) / col_stds
print("\nTask 3 Normalized Data (first row):\n", normalized_data[0])


Task 3 Normalized Data (first row):
 [ 1.46243196  1.31226855 -0.93116903]


# Vectorization vs. Loops

In [9]:
import time
arr = np.random.rand(1_000_000)
squared_vectorized = arr**2
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_ab = a + b
prod_ab = a * b
dist = np.linalg.norm(a - b) 
data = np.array([10, -5, 3, -1, 7])
cleaned_data = np.where(data < 0, 0, data)
start_loop = time.time()
loop_result = [x**2 for x in arr]
end_loop = time.time()
start_vec = time.time()
vec_result = arr**2
end_vec = time.time()

print(f"Loop time: {end_loop - start_loop:.4f}s")
print(f"Vectorized time: {end_vec - start_vec:.4f}s")

Loop time: 0.0971s
Vectorized time: 0.0024s


# Random Number Generator Toolkit

In [10]:
rand_uniform = np.random.rand(3, 4)
rand_normal_std = np.random.randn(5, 5)
rand_ints = np.random.randint(1, 101, size=10)
uniform_samples = np.random.uniform(5.0, 15.0, size=1000)
print(f"Uniform Mean: {uniform_samples.mean():.2f}")

scores = np.random.normal(70, 10, 500)
print(f"Scores -> Mean: {scores.mean():.2f}, Std: {scores.std():.2f}, Min: {scores.min():.2f}, Max: {scores.max():.2f}")

Uniform Mean: 9.94
Scores -> Mean: 70.28, Std: 9.94, Min: 43.18, Max: 98.73


# Mini Data Analysis Project

In [11]:
math = np.random.normal(75, 12, 100)
science = np.random.normal(68, 15, 100)
english = np.random.normal(80, 8, 100)

scores_matrix = np.column_stack((math, science, english))

scores_matrix = np.clip(scores_matrix, 0, 100)

student_averages = scores_matrix.mean(axis=1)
top_5_indices = np.argsort(student_averages)[-5:][::-1]
print(f"Top 5 Student Averages: {student_averages[top_5_indices]}")

subject_means = scores_matrix.mean(axis=0)
subject_vars = scores_matrix.var(axis=0)
subjects = ["Math", "Science", "English"]

print(f"Highest Mean Subject: {subjects[np.argmax(subject_means)]}")
print(f"Highest Variance Subject: {subjects[np.argmax(subject_vars)]}")

col_min = scores_matrix.min(axis=0)
col_max = scores_matrix.max(axis=0)
normalized_scores = (scores_matrix - col_min) / (col_max - col_min)

print("\nFirst 3 rows of normalized scores:")
print(normalized_scores[:3])

Top 5 Student Averages: [92.39087941 87.9846383  86.2331883  85.15240906 84.80560617]
Highest Mean Subject: English
Highest Variance Subject: Science

First 3 rows of normalized scores:
[[0.6779795  0.33851232 0.26721909]
 [0.36564692 0.64057315 0.58316347]
 [0.3540011  0.50516039 0.32509843]]
